robot_radius: 0.25
inflation_radius: 0.5
cost_scaling_factor: 10.0
obstacle_range: 3.5
raytrace_range: 4.0
observation_sources: base_lidar
track_unknown_space: false
base_lidar: {
    data_type: LaserScan,
    topic: /scan, 
    marking: true, 
    clearing: true
    }
footprint: [[-0.34, 0.32], [0.34, 0.32], [0.34, -0.32], [-0.34, -0.32]]
# footprint: [[-0.05, -0.05], [-0.05, 0.05], [0.05, 0.05], [0.05, -0.05]]